# Generated by Django 6.0.6 on 2026-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('pump_station', 'Pump Station'), ('borehole', 'Borehole'), ('reservoir', 'Reservoir')], max_length=20)),
                ('metric', models.CharField(choices=[('flow_rate', 'Flow Rate'), ('pressure', 'Pressure'), ('energy_kwh', 'Energy Kwh'), ('water_level', 'Water Level')], max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('warning', 'Warning'), ('fault', 'Fault')], max_length=10)),
            ],
            options={
                'db_table': 'readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['asset_id', '-recorded_at'], name='readings_asset_i_48df0d_idx'), models.Index(fields=['metric', '-recorded_at'], name='readings_metric_96c393_idx'), models.Index(fields=['recorded_at'], name='readings_recorde_87b25e_idx'), models.Index(fields=['status'], name='readings_status_013a66_idx')],
            },
        ),
    ]
