# Generated by Django 6.0.6 on 2026-07-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_reading_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='is_out_of_range',
            field=models.BooleanField(default=False),
        ),
    ]
